# screen propertied
WIDTH, HEIGHT = 800, 600
SCORE_HEIGT = 50

# Color properties
WHITE = (255, 255, 255)
BLACK = (37, 36, 40)

# Ball properties
BALL_RADIUS = 10
BALL_INIT_POS = (WIDTH // 2, HEIGHT // 2)
BAL_INIT_SPEED = [-1, 1]


# Paddle properties
PADDLE_WIDTH = 10
PADDLE_HEIGHT = 80
PADDLE_SPEED = 2
LEFT_PADDLE_INIT_POS = (0, (HEIGHT - PADDLE_HEIGHT) // 2)
RIGHT_PADDLE_INIT_POS = (WIDTH - PADDLE_WIDTH, (HEIGHT - PADDLE_HEIGHT) // 2)

# LINE PROPERTIES
LINE_WIDTH = 10
LINE_X = (WIDTH // 2, 0)
LINE_Y = (WIDTH // 2, HEIGHT)
